CREATE TABLE plate_number
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plate_number VARCHAR(255)                            NOT NULL,
    issued_date  date                                    NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    owner_id     UUID                                    NOT NULL,
    CONSTRAINT pk_platenumber PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           UUID         NOT NULL,
    first_name   VARCHAR(255) NOT NULL,
    last_name    VARCHAR(255) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    phone_number VARCHAR(10)  NOT NULL,
    national_id  VARCHAR(16)  NOT NULL,
    password     VARCHAR(255) NOT NULL,
    role         VARCHAR(255) NOT NULL,
    enabled      BOOLEAN      NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE vehicle
(
    id                  UUID         NOT NULL,
    chasis_number       VARCHAR(17)  NOT NULL,
    manufacturer        VARCHAR(255) NOT NULL,
    year_of_manufacture INTEGER      NOT NULL,
    price               DECIMAL      NOT NULL,
    model_name          VARCHAR(255) NOT NULL,
    current_owner_id    UUID         NOT NULL,
    plate_number_id     BIGINT       NOT NULL,
    CONSTRAINT pk_vehicle PRIMARY KEY (id)
);

CREATE TABLE vehicle_owners
(
    id           UUID        NOT NULL,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    phone_number VARCHAR(10) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    national_id  VARCHAR(16) NOT NULL,
    district     VARCHAR(16),
    sector       VARCHAR(16),
    CONSTRAINT pk_vehicle_owners PRIMARY KEY (id)
);

CREATE TABLE vehicle_transfer
(
    id                       UUID    NOT NULL,
    transfer_amount          DECIMAL NOT NULL,
    transfer_date            date    NOT NULL,
    vehicle_id               UUID    NOT NULL,
    previous_owner_id        UUID    NOT NULL,
    new_owner_id             UUID    NOT NULL,
    previous_plate_number_id BIGINT  NOT NULL,
    new_plate_number_id      BIGINT  NOT NULL,
    CONSTRAINT pk_vehicletransfer PRIMARY KEY (id)
);

ALTER TABLE plate_number
    ADD CONSTRAINT uc_platenumber_platenumber UNIQUE (plate_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_nationalid UNIQUE (national_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phonenumber UNIQUE (phone_number);

ALTER TABLE vehicle
    ADD CONSTRAINT uc_vehicle_chasisnumber UNIQUE (chasis_number);

ALTER TABLE vehicle_owners
    ADD CONSTRAINT uc_vehicle_owners_email UNIQUE (email);

ALTER TABLE vehicle_owners
    ADD CONSTRAINT uc_vehicle_owners_nationalid UNIQUE (national_id);

ALTER TABLE vehicle_owners
    ADD CONSTRAINT uc_vehicle_owners_phonenumber UNIQUE (phone_number);

ALTER TABLE vehicle
    ADD CONSTRAINT uc_vehicle_plate_number UNIQUE (plate_number_id);

CREATE UNIQUE INDEX idx_user_email_unq ON users (email);

CREATE UNIQUE INDEX idx_user_nationalid_unq ON users (national_id);

CREATE UNIQUE INDEX idx_user_phonenumber_unq ON users (phone_number);

CREATE INDEX idx_vehicle_chasisnumber ON vehicle (chasis_number);

ALTER TABLE plate_number
    ADD CONSTRAINT FK_PLATENUMBER_ON_OWNER FOREIGN KEY (owner_id) REFERENCES vehicle_owners (id);

ALTER TABLE vehicle_transfer
    ADD CONSTRAINT FK_VEHICLETRANSFER_ON_NEW_OWNER FOREIGN KEY (new_owner_id) REFERENCES vehicle_owners (id);

ALTER TABLE vehicle_transfer
    ADD CONSTRAINT FK_VEHICLETRANSFER_ON_NEW_PLATE_NUMBER FOREIGN KEY (new_plate_number_id) REFERENCES plate_number (id);

ALTER TABLE vehicle_transfer
    ADD CONSTRAINT FK_VEHICLETRANSFER_ON_PREVIOUS_OWNER FOREIGN KEY (previous_owner_id) REFERENCES vehicle_owners (id);

ALTER TABLE vehicle_transfer
    ADD CONSTRAINT FK_VEHICLETRANSFER_ON_PREVIOUS_PLATE_NUMBER FOREIGN KEY (previous_plate_number_id) REFERENCES plate_number (id);

ALTER TABLE vehicle_transfer
    ADD CONSTRAINT FK_VEHICLETRANSFER_ON_VEHICLE FOREIGN KEY (vehicle_id) REFERENCES vehicle (id);

ALTER TABLE vehicle
    ADD CONSTRAINT FK_VEHICLE_ON_CURRENT_OWNER FOREIGN KEY (current_owner_id) REFERENCES vehicle_owners (id);

ALTER TABLE vehicle
    ADD CONSTRAINT FK_VEHICLE_ON_PLATE_NUMBER FOREIGN KEY (plate_number_id) REFERENCES plate_number (id);